const peliculas = [
  {
    id: 1,
    titulo: "The Shawshank Redemption",
    generos: ["Drama"],
    anio: 1994,
    director: "Frank Darabont",
    likes: 1850,
    portada: "https://m.media-amazon.com/images/I/51NiGlapXlL._AC_.jpg",
  },
  {
    id: 2,
    titulo: "The Godfather",
    generos: ["Crime", "Drama"],
    anio: 1972,
    director: "Francis Ford Coppola",
    likes: 2100,
    portada: "https://m.media-amazon.com/images/I/71Mj1TyVPSL.jpg",
  },
  {
    id: 3,
    titulo: "The Dark Knight",
    generos: ["Action", "Crime", "Drama"],
    anio: 2008,
    director: "Christopher Nolan",
    likes: 2800,
    portada: "https://m.media-amazon.com/images/I/91KkWf50SoL._AC_SL1500_.jpg",
  },
  {
    id: 4,
    titulo: "Pulp Fiction",
    generos: ["Crime", "Drama"],
    anio: 1994,
    director: "Quentin Tarantino",
    likes: 1700,
    portada: "https://m.media-amazon.com/images/I/71zSZQzlK+L.jpg",
  },
  {
    id: 5,
    titulo: "Inception",
    generos: ["Action", "Adventure", "Sci-Fi"],
    anio: 2010,
    director: "Christopher Nolan",
    likes: 2600,
    portada: "https://m.media-amazon.com/images/I/A1eIBPcRUqL._AC_UF894,1000_QL80_.jpg",
  },
  {
    id: 6,
    titulo: "Fight Club",
    generos: ["Drama"],
    anio: 1999,
    director: "David Fincher",
    likes: 1900,
    portada: "https://m.media-amazon.com/images/I/51VNG7R87NL._AC_UF1000,1000_QL80_.jpg",
  },
  {
    id: 7,
    titulo: "Forrest Gump",
    generos: ["Drama", "Romance"],
    anio: 1994,
    director: "Robert Zemeckis",
    likes: 2400,
    portada: "https://m.media-amazon.com/images/I/71Kih9pBDyL._AC_UF1000,1000_QL80_.jpg",
  },
  {
    id: 8,
    titulo: "The Matrix",
    generos: ["Action", "Sci-Fi"],
    anio: 1999,
    director: "Lana Wachowski, Lilly Wachowski",
    likes: 2200,
    portada: "https://m.media-amazon.com/images/I/51vpnbwFHrL._AC_.jpg",
  },
  {
    id: 9,
    titulo: "Interstellar",
    generos: ["Adventure", "Drama", "Sci-Fi"],
    anio: 2014,
    director: "Christopher Nolan",
    likes: 2500,
    portada: "https://m.media-amazon.com/images/S/pv-target-images/79194981293eabf6620ece96eb5a9c1fffa04d3374ae12986e0748800b37b9cf.jpg",
  },
  {
    id: 10,
    titulo: "Gladiator",
    generos: ["Action", "Adventure", "Drama"],
    anio: 2000,
    director: "Ridley Scott",
    likes: 1800,
    portada: "https://m.media-amazon.com/images/I/81QVTiMK1wL._AC_UF894,1000_QL80_.jpg",
  },
  {
    id: 11,
    titulo: "Titanic",
    generos: ["Drama", "Romance"],
    anio: 1997,
    director: "James Cameron",
    likes: 2300,
    portada: "https://m.media-amazon.com/images/I/714-Er-OVhL._AC_UF894,1000_QL80_.jpg",
  },
  {
    id: 12,
    titulo: "The Lord of the Rings: The Fellowship of the Ring",
    generos: ["Adventure", "Drama", "Fantasy"],
    anio: 2001,
    director: "Peter Jackson",
    likes: 2600,
    portada: "https://m.media-amazon.com/images/I/51Qvs9i5a%2BL._AC_.jpg",
  },
  {
    id: 13,
    titulo: "The Silence of the Lambs",
    generos: ["Crime", "Drama", "Thriller"],
    anio: 1991,
    director: "Jonathan Demme",
    likes: 1700,
    portada: "https://m.media-amazon.com/images/I/91PATn10zTL._AC_UF1000,1000_QL80_.jpg",
  },
  {
    id: 14,
    titulo: "Saving Private Ryan",
    generos: ["Drama", "War"],
    anio: 1998,
    director: "Steven Spielberg",
    likes: 2100,
    portada: "https://m.media-amazon.com/images/I/81jwOAmgIvL._AC_UF894,1000_QL80_.jpg",
  },
  {
    id: 15,
    titulo: "The Green Mile",
    generos: ["Crime", "Drama", "Fantasy"],
    anio: 1999,
    director: "Frank Darabont",
    likes: 1800,
    portada: "https://m.media-amazon.com/images/I/81HdD8-7HaL.jpg",
  },
  {
    id: 16,
    titulo: "Whiplash",
    generos: ["Drama", "Music"],
    anio: 2014,
    director: "Damien Chazelle",
    likes: 1700,
    portada: "https://m.media-amazon.com/images/I/61FlrI8s5RL._AC_UF894,1000_QL80_.jpg",
  },
  {
    id: 17,
    titulo: "The Departed",
    generos: ["Crime", "Drama", "Thriller"],
    anio: 2006,
    director: "Martin Scorsese",
    likes: 1600,
    portada: "https://m.media-amazon.com/images/I/71TO1MtPQkL._AC_UF1000,1000_QL80_.jpg",
  },
  {
    id: 18,
    titulo: "Joker",
    generos: ["Crime", "Drama", "Thriller"],
    anio: 2019,
    director: "Todd Phillips",
    likes: 2300,
    portada: "https://m.media-amazon.com/images/I/81YdUDaMiWL._AC_UF894,1000_QL80_.jpg",
  },
  {
    id: 19,
    titulo: "Parasite",
    generos: ["Comedy", "Drama", "Thriller"],
    anio: 2019,
    director: "Bong Joon-ho",
    likes: 2100,
    portada: "https://m.media-amazon.com/images/I/71lrpAOFQJS._AC_UF894,1000_QL80_.jpg",
  },
  {
    id: 20,
    titulo: "The Prestige",
    generos: ["Drama", "Mystery", "Sci-Fi"],
    anio: 2006,
    director: "Christopher Nolan",
    likes: 1900,
    portada: "https://m.media-amazon.com/images/S/pv-target-images/a470c984db6c661eb4ba17989b7cbe43bb9f44223ec14592c3c4236c580934ba.jpg",
  },
  {
    id: 21,
    titulo: "The Social Network",
    generos: ["Biography", "Drama"],
    anio: 2010,
    director: "David Fincher",
    likes: 1600,
    portada: "https://m.media-amazon.com/images/I/81s3kbveNJL._AC_UF1000,1000_QL80_.jpg",
  },
  {
    id: 22,
    titulo: "Avengers: Endgame",
    generos: ["Action", "Adventure", "Drama"],
    anio: 2019,
    director: "Anthony Russo, Joe Russo",
    likes: 3000,
    portada: "https://m.media-amazon.com/images/I/81ExhpBEbHL._AC_SY679_.jpg",
  },
  {
    id: 23,
    titulo: "La La Land",
    generos: ["Comedy", "Drama", "Music"],
    anio: 2016,
    director: "Damien Chazelle",
    likes: 1800,
    portada: "https://m.media-amazon.com/images/I/51Sb8RIp70L._AC_UF1000,1000_QL80_.jpg",
  },
  {
    id: 24,
    titulo: "Django Unchained",
    generos: ["Drama", "Western"],
    anio: 2012,
    director: "Quentin Tarantino",
    likes: 2000,
    portada: "https://m.media-amazon.com/images/I/81IVfnsVtIL._AC_UF1000,1000_QL80_.jpg",
  },
  {
    id: 25,
    titulo: "Coco",
    generos: ["Animation", "Adventure", "Family"],
    anio: 2017,
    director: "Lee Unkrich",
    likes: 1900,
    portada: "https://m.media-amazon.com/images/I/71X9qLf+uIL._AC_UF1000,1000_QL80_.jpg",
  },
  {
    id: 26,
    titulo: "WALL·E",
    generos: ["Animation", "Adventure", "Family"],
    anio: 2008,
    director: "Andrew Stanton",
    likes: 1800,
    portada: "https://m.media-amazon.com/images/I/81K-KlDulqL._AC_UF894,1000_QL80_.jpg",
  },
  {
    id: 27,
    titulo: "The Lion King",
    generos: ["Animation", "Adventure", "Drama"],
    anio: 1994,
    director: "Roger Allers, Rob Minkoff",
    likes: 2500,
    portada: "https://m.media-amazon.com/images/I/81ETY9fq1YL.jpg",
  },
  {
    id: 28,
    titulo: "Toy Story",
    generos: ["Animation", "Adventure", "Comedy"],
    anio: 1995,
    director: "John Lasseter",
    likes: 2000,
    portada: "https://m.media-amazon.com/images/I/519N3V9KB9L._AC_UF894,1000_QL80_.jpg",
  },
  {
    id: 29,
    titulo: "Shrek",
    generos: ["Animation", "Adventure", "Comedy"],
    anio: 2001,
    director: "Andrew Adamson, Vicky Jenson",
    likes: 2100,
    portada: "https://m.media-amazon.com/images/I/81lCnhTXpRL._AC_UF894,1000_QL80_.jpg",
  },
  {
    id: 30,
    titulo: "Spider-Man: Into the Spider-Verse",
    generos: ["Animation", "Action", "Adventure"],
    anio: 2018,
    director: "Bob Persichetti, Peter Ramsey, Rodney Rothman",
    likes: 2200,
    portada: "https://m.media-amazon.com/images/I/81U65dgnBRL._AC_UF894,1000_QL80_.jpg",
  },
];
export default peliculas;
